name: Update native definitions

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * SUN

jobs:
  update-natives:
    if: github.actor_id != 210085057
    runs-on: ubuntu-latest
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest


      - name: Generate GitHub App token
        id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get latest code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}


      - name: Generate natives
        run: |
          wget https://github.com/communityox/rage-lua-natives/archive/master.zip -O repo.zip
          unzip repo.zip
          cd rage-lua-natives-master
          bun install --frozen-lockfile
          bun run start
          cd ..
          rm -rf library/natives/*
          mv -f rage-lua-natives-master/build/cfx/{CFX-NATIVE,GTAV,RDR3} library/natives/
          rm -rf rage-lua-natives-master
          rm repo.zip

      - name: Update repository
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          push: true
          default_author: github_actions
          message: 'ci: generate native definitions'
